# name: Test With My Action
# on:
#   push:
#     banches:
#       -Use_Action
# jobs: 
#   build_my_swift:
#     runs-on: ubuntu-latest
    
#     name: Build the Swift
#     run: swift build

#     name: Start the test
#     run: swift test

name: Test With My Action
on: 
  push:
    branches: ["Yumeng/use-actions"]

jobs:
  my-job:

    runs-on: ubuntu-latest

    steps:
      - name: Do Build
        run: swift build
      - name: Do Test  
        run: swift test