# name: Test With My Action
# on:
#   push:
#     banches:
#       -Use_Action
# jobs: 
#   build_my_swift:
#     runs-on: ubuntu-latest
    
#     name: Build the Swift
#     run: swift build

#     name: Start the test
#     run: swift test

name: Test With My Action
on: 
  push:
    branches: ["Yumeng/use-actions"]

jobs:
  my-job:

    runs-on: ubuntu-latest

    steps:

      # - name: Do excutable everywhere
      #   run: swift package init --type executable
      - name: Do Build
        work-dirctory: /home/runner/work/CS561_Week4/MyLibrary
        run: swift build
      - name: Do Test
        work-dirctory: /home/runner/work/CS561_Week4/MyLibrary
        run: swift test